# This GitHub Action is designed to build, publish, and release a .NET 7 project.
# The action is triggered when a commit is pushed to the `main` branch.
# The release is named using the timestamp of the commit in the format `Release_YYYYMMDDHHmm`.

name: Build and Release

# Specifies the event that triggers the workflow.
on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    # Specifies the type of runner that the job will run on.
    runs-on: ubuntu-latest

    steps:
    # Checks out the repository under $GITHUB_WORKSPACE, so the workflow can access it.
    - name: Checkout code
      uses: actions/checkout@v2

    # Extracts and formats the timestamp from the commit that triggered the workflow.
    - name: Extract timestamp
      id: timestamp
      run: |
        TIMESTAMP=$(echo "${{ github.event.commits[0].timestamp }}" | date -u -Iseconds -f- +'%Y%m%d%H%M')
        echo "::set-output name=formatted::$TIMESTAMP"
      shell: bash

    # Sets up a .NET 7 environment for the subsequent steps.
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    # Restores the dependencies of the .NET project.
    - name: Restore dependencies
      run: dotnet restore

    # Builds the .NET project in Release configuration without restoring dependencies.
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Publishes the .NET project to the `./out` directory without building.
    - name: Publish
      run: dotnet publish --configuration Release --no-build -o ./out

    # Creates a new release on GitHub using the formatted timestamp.
    # The release contains the built DLL from the .NET project.
    - name: Create Release and Upload DLL
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Release_${{ steps.timestamp.outputs.formatted }}
        release_name: Release_${{ steps.timestamp.outputs.formatted }}
        draft: false
        prerelease: false

    # Uploads the built DLL to the created release.
    - name: Upload DLL to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/GodotSharper.dll
        asset_name: GodotSharper.dll
        asset_content_type: application/octet-stream
